version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello-simple:
    lang: node20
    handler: ./hello-simple
    image: local/hello-simple:latest
  users-api:
    lang: node20
    handler: ./users-api
    image: local/users-api:latest
  orders-api:
    lang: node20
    handler: ./orders-api
    image: local/orders-api:latest

