name: CD - Production Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual execution

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build
  NODE_VERSION: '20'
  # Database configuration - PRODUCTION
  ENVIRONMENT: production
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME_DEV: ${{ secrets.DB_NAME_DEV }}
  DB_NAME_PROD: ${{ secrets.DB_NAME_PROD }}

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: [self-hosted, Linux, X64, webserver, fedora]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Load environment variables
      run: |
        echo "Loading production environment..."
        # The load_env.sh script will now use GitHub Actions variables
        source scripts/load_env.sh production
        echo "Environment loaded: $ENVIRONMENT"
        echo "Database: $DB_NAME_PROD"
        
    - name: Generate C++ config file
      run: |
        # Generate persistent configuration file for production
        sudo scripts/generate-cpp-config.sh production
        
    - name: Build and deploy
      run: |
        # Your build and deploy steps here
        mkdir -p ${{ env.BUILD_DIR }}
        cd ${{ env.BUILD_DIR }}
        cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        make -j$(nproc)